const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 3.4,
      numReviews: 8,
      countInStock: 25,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 12,
      countInStock: 25,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 80,
      brand: 'Raymond',
      rating: 3.4,
      numReviews: 3,
      countInStock: 25,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 80,
      brand: 'Raymond',
      rating: 4.4,
      numReviews: 23,
      countInStock: 25,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 85,
      brand: 'Gap',
      rating: 5.4,
      numReviews: 13,
      countInStock: 25,
      description: 'A popular pant',
    },
    {
      name: 'SlimPants',
      slug: 'slim-pants',
      category: 'Zara',
      image: '/images/pants3.jpg',
      price: 60,
      brand: 'Raymond',
      rating: 4.4,
      numReviews: 9,
      countInStock: 25,
      description: 'A popular pant',
    },
  ],
};

export default data;
